### ISSUE TITLE
Add missing banners for the Mavenseed products

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/website#149]
The mavenseed products, in the Products section, don't have a banner image, making them look like this:

![Screenshot from 2020-01-08 09-33-08](https://user-images.githubusercontent.com/12694995/71962518-e661ac80-31f9-11ea-8065-dc040837b968.png)

They should have the banners you can find attached below:

[banners.zip](https://github.com/GDQuest/website/files/4034230/banners.zip)

**Comment by razcore-art** [comment]
There's a new page that doesn't appear in the top screenshot for some reason. The home page for all the mavenseed courses which also needs a banner
![image](https://user-images.githubusercontent.com/1177508/72054254-50995080-32d1-11ea-94ba-128b26be85f2.png)

**Comment by razcore-art** [comment]
I pushed the banners to the available links/courses

**Comment by NathanLovato** [comment]
This one should be hidden, it's a link to the mavenseed website. We need these redirects because youtube only accepts links to your website, not external ones (except for kickstarter, gumroad, and a few others)

**Comment by razcore-art** [comment]
Alright, so @NathanLovato, I fixed this but I want to explain a few things. The way I'm filtering out the pages that aren't supposed to appear here is by missing `banner`s so if there's no banner set it won't show in the list at all. That's cause only-redirect pages won't have banners for sure, but that also means that you and anyone making product pages need to know that they'll only render in the list when a banner is assigned.

The banner is searched exclusively in `[[resources]]` so there's no need for the `[banner]` entry in the front matter. It was something I didn't understand, why is there `[banner]` and:
```toml
[[resources]]
name = "banner"
src = "path/to/banner.png"
```
Didn't make sense, so I investigated a bit and that's because `layouts/_default/summary.html` uses `resources` while `layouts/product/summary.html` was using `banner`. I just removed `layouts/product/summary.html` as it's redundant and also confusing to have defined both `[[resources]]` & `[banner]`.

I updated the archetypes accordingly as well although I don't know why there's `post` & `products` both folders & `.md` archetype folders & files as well. Maybe we need to look into that.

**Comment by NathanLovato** [comment]
> It was something I didn't understand, why is there [banner]

It was legacy data yes, the code needed some update.

Regarding archetypes, you can now have a directory for a type and hugo will instance the content of the directory based on the content you create. I thought I had replaced the single file with the directory versions but it seems it needs some cleanup. As posts and products should always have a banner, this is meant to create the content pages with a banner template in place.

https://gohugo.io/content-management/archetypes/#directory-based-archetypes
