### ISSUE TITLE
Godot: Team collaboration on medium/large size project using git

### ISSUE THREAD

**Issue by razcore-art** [GDQuest/website#86]
Write an outline for a post and video about collaborating on a Free game like we're doing with the Metroidvania example.

Nathan:
> I ran into a bit of trouble trying to merge everything, and I think it'd be a nice topic for a video.
> Some guidelines/best practices to work together as a team of devs working at different times like we are. Tips like creating inherited scenes or copies of scenes instead of working on the same base scene, those kinds of things

**Comment by NathanLovato** [comment]
> I don't see any other way than to make it clear that each individual developer is responsible for keeping up to date with master and have their feature/bugs codes in sync so they won't produce any merge conflicts.

Agreed! Each dev/contributor should rebase their branches and fix conflicts on their side.

> devs. create short-lived branches for bug fixes & feature additions that get merged as soon as they're ready

Yeah, that's kind of how we work. Instead of coding big systems and changes over a long period of time, everyone creates PRs for small features or bug fixes.

I'm all for doing development on master and tagging as well 🙂

In general, we should try to have everyone work on well-separated areas of the project, avoid possibilities of merge conflicts at all. If at some point we have to work on the same tscn file again in Godot, we should save branches as scenes at least temporarily, and merge them back later from Godot so that changes to the .tscn files get isolated from one another. The issue we've had with the Player scene was that it's one big scene everyone was working on.

With the state machine it already helps: you can create a state node and save it as a separate scene, not stage/commit changes to Player.tscn, just push your new node and changes to script files. It takes no time to later drag and drop the state node in the Player scene.
